---
title: '**Cover Letter**'
output:
  pdf_document:
    citation_package: natbib
    keep_tex: no
    latex_engine: pdflatex
    number_sections: no
    toc: no
linkcolor: Maroon
citecolor: Blue
urlcolor: Maroon
bibliography: bib/biblio.bib
biblio-style: bib/mee.bst
link-citations: yes
---

Dr. Ghislain Vieilledent 

CIRAD    
UPR Forêts et Sociétés    
F-34398 Montpellier    
FRANCE

Joint Research Center of the European Commission   
Bio-economy Unit (JRC.D.1)  
I-21027 Ispra (VA)  
ITALY

to

Editors    
_American Journal of Botany_ 

Object: Manuscript AJB-D-18-00085, answers to reviewers' comments.

####

Dear Editor,

Please find enclosed a new version of our article untitled _"New formula and conversion factor to compute tree species basic wood density from a global wood technology database"_. We thank the two Reviewers for their careful reading of our manuscript and their constructive remarks. We made our best to answer to Reviewers' comments and we modified our manuscript accordingly. We hope that you will find this new version of our article suitable for publication in _American Journal of Botany_.

Best regards,

The authors

# Associate Editor's comment

**Dear authors,**

**Thank your for giving us the opportunity to review your manuscript for publication in the American Journal of Botany. We have now received two reviews of your manuscript, both of which were favorable. Based on the advice received from the reviewers and my own evaluation, there are a number of minor issues that will require your attention before the manuscript can be recommended for publication. Both reviewers liked the manuscript and find that it will make a significant advancement in the field, but some additional clarification and edits need to be made.**

**Sincerely,**

**Craig R. Brodersen**
**Associate Editor**

# Answers to remarks by Reviewer 1

**The study "New formula and conversion factor to compute tree species basic wood density from a global wood technology database" is based on a solid dataset and could be an important contribution for future forest (modelling) ecology studies. In that regard it is not necessary to "advertise" the new model throughout the manuscript. The manuscript could benefit from shortening, there are some repeats and some messages in the introduction and discussion are rather vague and would profit from a more detailed recherche of relevant ecophysiological literature. Some methodological details are as well not clear to me. Also some analysis approaches are not logical, for instance when a tree mean value is produced from several measurements along the stem. Please find more specific comments below.**

We provide below answers to Reviewer 1's remarks on some methodological details. We hope our explanations and the modifications of the text will make these methodological points appear clearer and more logical.

## Abstract

**Lines 20-21, it does not overestimate basic wood density when compared to Reyes' relationship.**

We have modified the sentence to be more specific:     

"This value of 0.828 provides basic wood density estimates 4-5% smaller than values inferred from previous conversion factors."

## Introduction

**Line 30, plants**

Corrected.

**Line 33, wood density is not directly related to physiological functions, see Lachenbruch and McCulloh, 2014. New Phytologist 204: 747-764. <doi:10.1111/nph.13035>**

We totally agree. In the introduction, we just underline that wood density has strong correlations with many measures of plant performance (as acknowledged in the abstract and text of Lachenbruch and McCulloh, 2014), even if without direct causality. We modified the text and added the suggested reference:     

"In community ecology, wood density is a proxy for species performance (Lachenbruch & McCulloh, 2014), reflecting a trade-off
between growth potential and mortality risk from biomechanical or hydraulic failure (Diaz et al. , 2016). Fast-growing, short-lived species tend to have a lower wood density while slow-growing, long-lived species tend to have a higher wood density (Chave et al., 2009; Greenwood et al., 2017)."

**Line 34, wood density, forests**

Corrected.

**Line 35, climate change**

Corrected.

**Line 40, see also the publication of: Greenwood et al. 2017. Ecology Letters, 20: 539-553**

We have added the reference to the text.

**Lines 43-44, rephrase this sentence, or just skip it**

We reformulated: "This explains why wood density has been commonly measured in forestry institutes, where wood was principally studied for construction or paper making."

**Line 45, this literature should be also cited, since there are conversion tables in Chapter 4: Forest Products Laboratory. 2010. Wood handbook—Wood as an engineering material. General Technical Report FPL-GTR-190. Madison, WI: U.S. Department of Agriculture, Forest Service, Forest Products Laboratory. 508 p.**

We have added this reference here and also in section 2.1.2 "Measuring wood mass, moisture content, and volume".

**Line 53, "green volume" is a rather vague terminology, as is water saturated, because volumetric changes can occur also above fiber saturation, see Rosner et al., 2009 Tree Physiology 29: 1419-1431. <doi:10.1093/treephys/tpp077>**

We agree that this terminology is debatable. Nonetheless, the term green volume is commonly used in wood technology, see for example p. 9 of Chapter 4 of the previously suggested reference: 

"Commonly used bases for volume are (a) ovendry, (b) green, and (c) 12% moisture content."

"The combination of ovendry mass and green volume is referred to as basic specific gravity Gb"

Moreover, we now discuss the theory around the definition of the fibre saturation point in the Discussion part.

**Line 110, make a paragraph here**

Done.

## Materials and Methods

**Lines 137-138, whenever dropping names give also the citations (even if the citation is repeated).**

We have added the citations.

**Lines 139-159, it is not clear if the study makes use of existing data (because there are several methods described) or performed new measurements. Please clarify and provide a table (or add to Table 1) all samples where the full dataset was available, meaning R, S and both densities.**

The study only make use of historical existing data. We now specify this more clearly at the end of section 2.1.3 "Measuring fibre saturation point, volumetric shrinkage coefficient, and wood density at 12% moisture":     

"In the Cirad database, average values for $S$, $R$ and $D_{12}$ for each tree were historically recorded using $>10$ wood samples taken at various positions in the trunk. Out of the 4022 trees present in the Cirad database, 190 trees had only measurements for $D_{12}$, with no values for $S$ and $R$. Definitions and units of wood physical and mechanical properties used in the present study are all summarized in Supp. Info. S1."

**Lines 162-204, how many measurements new or existing? Please provide a table**

See previous answer.

**Line 166, see Rosner et al. (2009), wood can shrink as well already above fiber saturation, this should be mentioned.**

We now discuss the theory around the definition of the fibre saturation point in the Discussion part (section 4.3). We added the suggested reference to the text.

**Lines 168-170, did you use green wood for your experiments? Wood that was once dried is difficult to re-saturate and shows different shrinkage behavior.**

From the field to the laboratory, wood samples might have experienced some drying during the transport and storage. That's why wood samples were re-saturated: "wood samples were autoclaved, subjected to one hour of vacuum (to accelerate water impregnation) and then soaked in water during 15 hours at 5 bar pressure". We have now underlined this limitation in the Discussion part (section 4.3).

## Discussion

**Lines 328-330, since there is not much difference thus a better argumentation should be found!**

We provide arguments about why the value of 0.828 derived from our approach should be preferred to the value of 0.821 derived from Reyes' relationship: 

"The conversion factor of 0.828 is based on a larger and more consistent database than the one used by Reyes (1992). Database used by Reyes combined density data at the species and genera level and included air-dry densities not stabilized at 12\% (Chudnoff 1984)."

The value of 0.821 derived from Reyes's relationship just reinforce our findings saying that the conversion factor value of 0.828 should be prefered to the values of 0.861 or 0.872 previously used in the literature.

**Lines 332-360, this chapter could be shortened and traits could be explained better**

We made our best to shorten that part. Regarding traits described in this part, please see the answer below for lines 346-350.

**Line 336, 201 additional tree species**

Corrected.

**Lines 338-340, this sentence is really not necessary! It may be put in the methods part.**

We removed this sentence from the discussion. In the method part, we have added the following lines in section 2.1.3:

"Given the precision of wood mass and volume measurements (see sec. 2.1.2), uncertainty regarding wood densities at 12\% moisture for individual samples was considered to be of about 0.01 g/cm$^3$.""

**Lines 346-350, please explain this better; plant physiologists are not used to this terminology, mention also "free water" and that "bound water" is water in the cell walls and capillary water**

In the first version of the manuscript, we referred to the terminology used in Berry and Roderick, 2005. The terms "solid" and "liquid" water were introduced by physical chemist and wood scientist A. J. Stamm. We agree that using the terms "free water" and "bound water" here would more consistent, as we have already introduced this terms when defining the fibre saturation point $S$ in section 2.1.3. The term "fresh" was also replaced by "green". We thus modified the text:     

"The fibre saturation point is an essential wood characteristic that can be used, in combination with the green volume, the green mass and the dry mass, to estimate the volume of water for each of the three bulk phases in a tree: (1) "free" liquid water in cell lumens and cavities, (2) water vapor in the gas-filled voids, and (3) "bound" water held chemically within cell walls (sometimes also called "solid" water, see Berry and Roderick, 2005). The volume of "bound" water is an essential plant functional trait as it determines wood strength and constraints on plant architecture (Niklas, 1993), as is the volume of "free" liquid water which is the ultimate source of the biochemical activity in living plants (Berry and Roderick, 2005)."

**Lines 351-354, I do not understand the logics of this argumentation (Lines 355-356). The mean value is contra productive regarding the variability that is possible within a tree, what is the advantage of this? I would expect that is better to include the point measurements along the trunk in order to include the within tree variability. See Rosner (2017) Journal of Plant Hydraulics. <https://doi.org/10.20870/jph.2017.e001>**     
**Could you provide a regression for the single data points? In a supplement figure?**

We totally agree with the reviewer that it would have been preferable to provide point measurements along the trunk in the database to be able to estimate within tree variability (also called intra-individual variability). Unfortunately, it is the average of >10 samples at the tree level which has been historically recorded in the Cirad database, with the underlying assumption that intra-specific and inter-specific variability was greater than intra-individual variability. We have modified the text in the Methods and Discussion parts (section 2.1.3) to be clearer:     

"In the Cirad database, average values for $S$, $R$ and $D_{12}$ for each tree were historically recorded using $>10$ wood samples taken at various positions in the trunk."

Nonetheless, as we say in the text, the Cirad database can be used to estimate the intra-specific and inter-specific variability of the wood characteristics available in the database.

**Line 364, forests**

Corrected.

**Line 366, literature**

Corrected.

**Line 375 basic wood density**

Corrected.

**Lines 371-377, this part is confusing: what do you derive from what for which purpose - compare that to you message in line 58-60, there it is written that from basic density the carbon stock is derived; you are calculating basic density from dry (12%) wood density, then you would overestimate the carbon stock, right? On the other hand, when you calculate dry density (12%) from basic density you will receive a higher basic wood density. It would be helpful to explain this with regard of the differences in the volume in the fully saturated state and the volume at 12% and the consequences for modeling the carbon stock, since it seems that in earlier studies the volumetric changes were underestimated!**

We think there is a misunderstanding here. As underlined in the introduction (lines 58-65), basic wood density (dry mass/green volume) is used to compute tree dry biomass from estimated standing tree volume (green volume). Empirical studies have shown that dry biomass can be converted to carbon stock using the carbon fraction of 0.47 (McGroddy et al., 2004). 

Although it would have been statistically possible to derive allometric models to estimate dry biomass from wood density at 12% moisture (mass at 12%/volume at 12%), this makes less sense on a theoretical point of view, and to our knowledge no scientific study has published such models.

In this part of the discussion, we just discuss the fact that basic wood densities in the Global Wood Density Database (GWDD) are overestimated by +3.05% on average. This is in line with the fact that 60% of the basic wood densities in the GWDD have been derived from an overestimated conversion factor of 0.861.

Consequently, studies using basic wood density values from GWDD to compute tree biomass are likely to provide overestimated forest carbon stock values.

**Lines 380-387, there are newer studies (Greenwood et al. 2017.) and also more critic studies, see Anderegg et al. (2015) PNAS <www.pnas.org/cgi/doi/10.1073/pnas.1525678113>**

We modified the text including a citation to Greenwood et al. 2017 study:     

"This study will also provide a firmer basis for future ecological research on wood density as a functional trait. Indeed, wood density is often considered as a key tree functional trait determining species performance and fitness (Baraloto et al., 2010; Chave et al., 2009; Diaz et al., 2016; Greenwood et al., 2017; Kunstler et al., 2016). For example, recent global studies have demonstrated that values of wood density explained the competition outcome between pairs of tree species (Kunstler et al., 2016), and that drought-induced mortality was promoted by lower wood densities (Greenwood et al., 2017). Using a wood density database with unbiased values of basic wood densities would allow proper estimates of species' differences with regards to this trait and predict better the dynamics of tree species community."

**Table 1, provide the number of samples that were measured for the study**

This number is now provided in the text, section 2.1.3 "Measuring fibre saturation point, volumetric shrinkage coefficient, and wood density at 12% moisture":     

"In the Cirad database, average values for $S$, $R$ and $D_{12}$ for each tree were historically recorded using $>10$ wood samples taken at various positions in the trunk. Out of the 4022 trees present in the Cirad database, 190 trees had only measurements for $D_{12}$, with no values for $S$ and $R$. Definitions and units of wood physical and mechanical properties used in the present study are all summarized in Supp. Info. S1."

**Table 2, refer to Table S1**

Done.

We thank Reviewer 1 for his/her careful review of our manuscript and the additional relevant references he/she provided.

# Answers to remarks by Reviewer 2

## Main comments

**The manuscript defines the relationship between basic wood density (0% moisture content) and classically defined "air dry" wood density (12% or 15% MC). The authors provide a theoretical justification for the relationship which includes a volumetric shrinking coefficient where shrinkage is a function of moisture lost once the fiber saturation point has been passed. More importantly, the authors determine the empirical relationship between basic density and density at 12% and 15% MC from a large sample of woods.**

**Although the difference between the new relationship and prior relationships appears to be a relatively small bias 3-4%, the importance of such differences to models of global carbon balance should not be overlooked. Such models compare CO2 inputs to Carbon fixation rates, so a few percent can result in major differences in CO2 accumulation rates and hence rates of global climate change.**

**Overall, the manuscript is a meaningful contribution, which is likely to be widely cited and referenced, by ecologists and foresters as well as the few remaining plant anatomists in the world.**

Thanks for your positive comments.

**I would recommend the authors add a small section about limits of their study which might include:**

**1. A statement about tropical vs temperate woods. The authors state that their sample is mostly tropical woods, but it should be noted that median Db is 0.60 whereas most temperate angiosperms fall into the 0.3-0.7 class. Therefore, the percent bias in previous studies is likely to be small for temperate woods relative to prior studies of tropical woods.**

**2. The authors might note the composition of the datasets in regard to gymnosperms and angiosperms.**

**3. Within the data base, there are relatively few low density woods, one at 0.19 and at most a dozen in the range 0.2-03, as I judge from Fig 2.  This is probably a bias of past sampling by foresters whose interests rested in structural woods. But it should be noted because these woods often have large bands of parenchyma alternating with fibers, so they may exhibit a different relationships between basic and airdry densities. The authors could test this with the lower density woods in their database.**

**4. I'm sure the authors know that the relationships discussed are not chemically "ideal" - for examples, not all free water is lost before some bound water is lost, and some low molecular weight organic compounds are lost during drying. The analogy of ideal gas laws and real gas relationships is clear. It might be useful to note this for young scientists endeavoring to determine densities of their wood samples - a given wood sample may vary somewhat from the relationships described in this MS.**

We added a section to discuss each of these points in the Discussion part (section 4.3) and in Supplementary Information S3.

**Fig. 1 is unnecessary, and it duplicates the Table 1.**

In Tab. 1, we list countries with more than 20 tree species in the Cirad wood density database. In Fig. 1, we identify every countries with at least one tree species. We think Fig. 1 is useful and complementary to Tab. 1 as it provides information on the spatial repartition of the data at the global scale (total extent of the data, total number of countries, temperate vs. tropical, data abundance per country, etc.). We have thus decided to retain that figure in the new version of the manuscript, modifying its title and legend to better describe the information it provides:      

"Figure 1: **Global repartition of the data available in the Cirad wood density database.** Data repartition is provided in number of species per country. Most of the species in the database (830/872) are found in the tropics (materialized by the grey band on the map)."

## Minor suggestions

**Here are some minor suggestions for syntax and orthography.**     
**line 5 delete "for construction purposes"**

Corrected.

**line 5 add "it is convenient for ecological purposes"**

Corrected

**line 34 do not hyphenate wood-density**

Corrected.

**line 35 do not hyphenate climate-change**

Corrected.

**line 98 "address" should be "addressing"**

Corrected.

**line 157 "measuring" should be "to measure"**

Corrected.

**line 366 "litterature" should be "literature" [lol]**

Corrected.

**line 386 "allow to properly estimate species difference" should be "allow proper estimates of species' differences"**

Corrected.

**line 389 "warmely" should be "warmly"**

Corrected.

**Congratulations to the authors,**     
**--G. Bruce Williamson**

We thank G. Bruce Williamson for his careful review of our manuscript.
